# fly.toml app configuration file generated for backend-spring-wind-8770 on 2025-09-05T01:28:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-spring-wind-8770'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.concurrency]
    type = "requests"
    soft_limit = 500
    hard_limit = 550

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1


[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"